// Dev-only asset bundler. Run once per manifest/art change:
//   node js/dev/fetch-assets.mjs [--offline]
//
// 1. Fetches Phosphor Icons (MIT, github.com/phosphor-icons/core) named in
//    MANIFEST and writes js/ui/icons.js (inline duotone markup + fill path
//    data for canvas). All-or-nothing: any failure aborts without touching
//    committed output. --offline skips fetching and only rebundles art.
// 2. Bundles every hand-authored SVG under assets/art/** into js/ui/art.js
//    (PRODUCT_ART / STAMP_ART / BRAND_ART / GURU_ART + unique-id helpers).
//
// The generated files are committed — the game never fetches at runtime.

import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync, readdirSync, existsSync } from 'node:fs';
import { join, basename } from 'node:path';

const ROOT = new URL('../..', import.meta.url).pathname;
const BASE = 'https://raw.githubusercontent.com/phosphor-icons/core/main/assets';

// weight: 'duotone' → ICONS[name]; 'fill' → ICON_PATHS[name] (canvas pins)
const DUOTONE = [
  // nav + chrome
  'gauge', 'package', 'film-slate', 'arrow-fat-lines-up', 'chart-line-up',
  'crown', 'trophy', 'gear-six', 'lock-simple',
  // kpi bar
  'eye', 'lightning', 'users-three', 'moon', 'sun', 'speaker-high', 'speaker-slash',
  // ad studio
  'dice-five', 'rocket-launch', 'brain', 'waves', 'trend-up', 'target',
  'sparkle', 'timer', 'broadcast', 'diamonds-four',
  // outcomes (mega is a custom glyph)
  'skull', 'smiley-meh', 'flame', 'rocket',
  // economy & actions
  'megaphone', 'coins', 'hand-coins', 'storefront', 'bank', 'handshake',
  'scroll', 'envelope-open', 'wallet', 'piggy-bank',
  // progression & meta
  'medal', 'certificate', 'star', 'gift', 'alarm', 'sun-horizon',
  'hourglass-high', 'arrow-counter-clockwise', 'confetti', 'list-checks',
  // team
  'robot', 'baseball-cap', 'clipboard-text', 'user-circle', 'student',
  // niches / tree pool
  'paw-print', 'flower-lotus', 'knife', 'bed', 'drop', 'atom', 'plug',
  'armchair', 'barbell', 'detective', 'crosshair', 'graduation-cap',
  'microphone-stage', 'globe-hemisphere-west', 'printer', 'sailboat',
  'buildings', 'mountains', 'fish', 'mask-happy', 'binoculars', 'coffee', 'dog',
  // settings / system
  'corners-out', 'shield-check', 'upload-simple', 'download-simple',
  'question', 'share-network', 'device-mobile', 'wrench', 'bell-ringing',
  'chat-teardrop-text', 'play-circle', 'chats-circle', 'paper-plane-tilt',
  'camera', 'music-notes', 'heartbeat', 'strategy',
];
const FILL = ['rocket', 'flame', 'skull', 'smiley-meh', 'waves', 'fish', 'star', 'sparkle'];

const offline = process.argv.includes('--offline');

function curl(url) {
  return execFileSync('curl', ['-sf', '--max-time', '30', url], { encoding: 'utf8' });
}

function inner(svg) {
  const m = svg.match(/<svg[^>]*>([\s\S]*)<\/svg>/);
  if (!m) throw new Error('no <svg> wrapper');
  return m[1].trim().replace(/\s+/g, ' ');
}

function pathData(svg) {
  const m = svg.match(/\sd="([^"]+)"/);
  if (!m) throw new Error('no path d=');
  return m[1];
}

// --- 1. Icons -----------------------------------------------------------------
const iconsOut = join(ROOT, 'js/ui/icons.js');
if (!offline) {
  const icons = {};
  const paths = {};
  const failed = [];
  for (const name of [...new Set(DUOTONE)]) {
    try { icons[name] = inner(curl(`${BASE}/duotone/${name}-duotone.svg`)); }
    catch { failed.push(`duotone/${name}`); }
  }
  for (const name of FILL) {
    try { paths[name] = pathData(curl(`${BASE}/fill/${name}-fill.svg`)); }
    catch { failed.push(`fill/${name}`); }
  }
  // Custom glyphs (256 grid) merge in — e.g. the mega-viral volcano Phosphor lacks.
  const glyphDir = join(ROOT, 'assets/art/glyphs');
  if (existsSync(glyphDir)) {
    for (const f of readdirSync(glyphDir).filter((f) => f.endsWith('.svg'))) {
      const name = basename(f, '.svg');
      const svg = readFileSync(join(glyphDir, f), 'utf8');
      icons[name] = inner(svg);
      try { paths[name] = pathData(svg); } catch { /* multi-path glyph: no canvas use */ }
    }
  }
  if (failed.length) {
    console.error(`ABORT — ${failed.length} fetch failures (output untouched):\n  ${failed.join('\n  ')}`);
    process.exit(1);
  }
  const header = `// GENERATED by js/dev/fetch-assets.mjs — do not hand-edit.
// Phosphor Icons (https://github.com/phosphor-icons/core), MIT License,
// © Phosphor Icons. Custom glyphs from assets/art/glyphs/ (project license).
// 256-grid inner markup; tint via currentColor (duotone back-layer baked).
`;
  const body = `${header}
export const ICONS = ${JSON.stringify(icons)};

export const ICON_PATHS = ${JSON.stringify(paths)};

export function icon(name, opts = {}) {
  const { size = 16, cls = '' } = opts;
  return \`<svg class="ph\${cls ? ' ' + cls : ''}" width="\${size}" height="\${size}" viewBox="0 0 256 256" fill="currentColor" aria-hidden="true">\${ICONS[name] || ICONS.question}</svg>\`;
}
`;
  writeFileSync(iconsOut, body);
  console.log(`icons.js: ${Object.keys(icons).length} duotone, ${Object.keys(paths).length} fill paths, ${(body.length / 1024).toFixed(1)} KB`);
}

// --- 2. Hand-authored art -------------------------------------------------------
const GROUPS = { products: 'PRODUCT_ART', stamps: 'STAMP_ART', brand: 'BRAND_ART', guru: 'GURU_ART' };
const bundles = {};
for (const [dir, exportName] of Object.entries(GROUPS)) {
  const p = join(ROOT, 'assets/art', dir);
  bundles[exportName] = {};
  if (!existsSync(p)) continue;
  for (const f of readdirSync(p).filter((f) => f.endsWith('.svg'))) {
    const raw = readFileSync(join(p, f), 'utf8').trim().replace(/\s+/g, ' ').replace(/> </g, '><');
    bundles[exportName][basename(f, '.svg')] = raw;
  }
}
const artHeader = `// GENERATED by js/dev/fetch-assets.mjs from assets/art/** — do not hand-edit.
// Hand-authored for Ship Happens (project license). Gradient/mask ids use the
// __u__ placeholder; the helpers suffix them per call so the same art can
// render in several places at once without duplicate-id breakage.
`;
const artBody = `${artHeader}
export const PRODUCT_ART = ${JSON.stringify(bundles.PRODUCT_ART)};
export const STAMP_ART = ${JSON.stringify(bundles.STAMP_ART)};
export const BRAND_ART = ${JSON.stringify(bundles.BRAND_ART)};
export const GURU_ART = ${JSON.stringify(bundles.GURU_ART)};

// Memoized per (art, size, cls): identical instances share def ids — the
// browser resolves url(#id) to the first matching def, which is identical
// markup, so repeats render correctly AND string-diff caches stay stable.
const memo = new Map();
let uid = 0;
function instance(key, svg, w, h, cls) {
  if (!svg) return '';
  const k = \`\${key}|\${w}|\${h}|\${cls}\`;
  let out = memo.get(k);
  if (!out) {
    const u = 'a' + (uid++).toString(36);
    out = svg.replaceAll('__u__', u)
      .replace('<svg ', \`<svg width="\${w}" height="\${h}"\${cls ? \` class="\${cls}"\` : ''} aria-hidden="true" \`);
    memo.set(k, out);
  }
  return out;
}
export function productArt(id, size = 34, cls = '') { return instance('p' + id, PRODUCT_ART[id], size, size, cls); }
export function stampArt(id, w = 128, cls = '') { return instance('s' + id, STAMP_ART[id], w, w / 2, cls); }
export function brandArt(id, size = 32, cls = '') { return instance('b' + id, BRAND_ART[id], size, size, cls); }
export function guruArt(mood = 'grind', size = 40, cls = '') { return instance('g' + mood, GURU_ART['guru-' + mood], size, size, cls); }
`;
writeFileSync(join(ROOT, 'js/ui/art.js'), artBody);
const counts = Object.entries(bundles).map(([k, v]) => `${k}:${Object.keys(v).length}`).join(' ');
console.log(`art.js: ${counts}, ${(artBody.length / 1024).toFixed(1)} KB`);
